# Generated by Django 5.2.8 on 2025-11-17 17:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 17, 17, 43, 42, 903460, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='reassignment_rule',
            field=models.CharField(choices=[('on_create', 'Every time a new task is created'), ('after_n_tasks', 'After x tasks are created'), ('after_n_weeks', 'After x weeks pass')], default='on_create', max_length=50),
        ),
        migrations.CreateModel(
            name='ExternalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=20)),
                ('secret', models.JSONField(help_text='JSON blob of OAuth2 tokens, including access and refresh tokens')),
                ('account_email', models.EmailField(blank=True, help_text='Email of the provider account if available', max_length=254, null=True)),
                ('scopes', models.TextField(blank=True, help_text='Scopes granted during OAuth login (for debugging or extension)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiry datetime of the OAuth2 access token', null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True, help_text='When the token was last refreshed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Credential',
                'verbose_name_plural': 'External Credentials',
                'unique_together': {('user', 'provider', 'account_email')},
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_choice', models.CharField(choices=[('none', 'No repeat'), ('every_n_days', 'After x days')], default='none', max_length=50)),
                ('recur_value', models.PositiveIntegerField(blank=True, help_text='Used to store n for n_days', null=True)),
                ('next_due', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, help_text='User who created this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chore_sync.group')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook'), ('internal', 'Built-in Calendar')], default='internal', max_length=20)),
                ('external_id', models.CharField(blank=True, default=None, help_text='ID used by external provider to identify the calendar', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the calendar to display in the UI', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional user-provided description for the calendar', null=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('back_sync_enabled', models.BooleanField(default=False, help_text='Push app events to external provider?')),
                ('sync_token', models.CharField(blank=True, help_text='Provider-specific sync token for incremental sync', max_length=512, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this calendar was last synced', null=True)),
                ('sync_window_days', models.PositiveIntegerField(default=365, help_text='Sync events within X days from now')),
                ('default_reminder_minutes', models.IntegerField(blank=True, help_text='Default reminder time in minutes before event start', null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone identifier', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Display color for the calendar (if supported by provider)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, help_text='OAuth2 credentials used to sync this calendar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to='chore_sync.externalcredential')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'unique_together': {('user', 'provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TaskOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Current assignee for the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chore_sync.tasktemplate')),
            ],
            options={
                'ordering': ['deadline'],
                'unique_together': {('template', 'deadline')},
            },
        ),
    ]
