# Generated by Django 5.2.8 on 2025-11-20 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0002_groupmembership_joined_at_alter_group_group_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='include_in_availability',
            field=models.BooleanField(default=True, help_text='If False, events from this calendar are ignored in free-time computation.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_reassigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last reassignment', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='reassignment_value',
            field=models.PositiveIntegerField(blank=True, help_text='Used to store n for n_tasks and n_weeks', null=True),
        ),
        migrations.CreateModel(
            name='GroupCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', help_text="Timezone used when aggregating the group's calendar.", max_length=50)),
                ('show_member_calendars', models.BooleanField(default=True, help_text="If True, include members' personal calendars in the group view.")),
                ('show_group_tasks', models.BooleanField(default=True, help_text='If True, include task-derived events in the group calendar.')),
                ('color', models.CharField(blank=True, help_text='Optional default color for group events.', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to='chore_sync.group')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chore_sync.group')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current approval state of the proposal.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional explanation for why this task should be added.')),
                ('voting_deadline', models.DateTimeField(blank=True, help_text='When proposal will expire if not decided before this deadline.', null=True)),
                ('required_support_ratio', models.FloatField(default=0.5, help_text='Minimum fraction of supporting votes to approve, once all members have voted.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the proposal was approved (if applicable).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='Group this proposal was put forward to.', on_delete=django.db.models.deletion.CASCADE, related_name='task_proposals', to='chore_sync.group')),
                ('proposed_by', models.ForeignKey(blank=True, help_text='User who created this proposal (may be null if deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_proposals', to=settings.AUTH_USER_MODEL)),
                ('task_template', models.ForeignKey(help_text='The underlying task template being proposed.', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='chore_sync.tasktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current state of this swap request.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional explanation / justification for proposing the swap.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, help_text='When the swap was accepted/rejected/cancelled (if applicable).', null=True)),
                ('from_user', models.ForeignKey(blank=True, help_text='User who proposed the swap (may be null if user was deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swaps_initiated', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='chore_sync.taskoccurrence')),
                ('to_user', models.ForeignKey(blank=True, help_text='User who accepted the swap (null while pending/open-ended).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swaps_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('external', 'External calendar event'), ('task', 'Generated from a task occurrence'), ('manual', 'Manual in-app event')], default='manual', help_text='Where this event originated (external feed, task, or manual).', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False, help_text='Treat as an all-day event when rendering / syncing.')),
                ('blocks_availability', models.BooleanField(default=True, help_text='If False, this event is ignored when computing free time.')),
                ('external_event_id', models.CharField(blank=True, help_text="ID of this event in the external provider's calendar API.", max_length=255, null=True)),
                ('external_calendar_id', models.CharField(blank=True, help_text="Provider's calendar ID at the time of sync (for safety).", max_length=255, null=True)),
                ('status', models.CharField(default='confirmed', help_text='confirmed / cancelled / tentative / etc.', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, help_text='Optional raw provider payload for debugging and edge cases. Only populated in DEBUG for external events.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chore_sync.calendar')),
                ('task_occurrence', models.OneToOneField(blank=True, help_text='Task occurrence that generated this event (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='chore_sync.taskoccurrence')),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['calendar', 'start'], name='chore_sync__calenda_e95a2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(blank=True, help_text='When the user first read the message (null = not seen yet).', null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chore_sync.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TaskPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('prefer', 'Prefer'), ('neutral', 'Neutral'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional explanation of this preference.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this preference was last changed.')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='chore_sync.tasktemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task_template')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_swap', 'Task swap'), ('group_invite', 'Group invite'), ('task_proposal', 'Task proposal'), ('message', 'Message')], max_length=50)),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, help_text='Group this notification relates to (if any).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chore_sync.group')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chore_sync.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chore_sync.taskoccurrence')),
                ('task_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chore_sync.taskproposal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='chore_sync__recipie_48e98e_idx'), models.Index(fields=['recipient', 'created_at'], name='chore_sync__recipie_90e843_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('support', 'Support'), ('reject', 'Reject'), ('abstain', 'Abstain')], help_text="The member's decision for this proposal.", max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional comment or reasoning for the vote.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(help_text='The proposal being voted on.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chore_sync.taskproposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task vote',
                'verbose_name_plural': 'Task votes',
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
