# Generated by Django 5.2.8 on 2025-11-26 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0003_calendar_include_in_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='importance',
            field=models.CharField(choices=[('core', 'Core'), ('additional', 'Additional')], default='core', help_text='Core tasks are considered essential for new members; additional tasks can be bulk-set to neutral on join.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_streak_date',
            field=models.DateField(blank=True, help_text='Date on which the streak was last updated.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_on_time_streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Longest historical on-time streak in days.'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_time_streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive days the user has met all task deadlines.'),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='task_template',
            field=models.ForeignKey(blank=True, help_text="The underlying task template being proposed - if the proposal isn't accepted - we'll keep this for history.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='chore_sync.tasktemplate'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
