# Generated by Django 5.2.12 on 2026-03-10 16:55

import chore_sync.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0009_calendar_webhooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('criteria', models.JSONField(help_text="e.g. {'streak_days': 30}")),
                ('points_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('tasks_completed_this_week', models.PositiveIntegerField(default=0)),
                ('tasks_completed_this_month', models.PositiveIntegerField(default=0)),
                ('on_time_completion_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskoccurrence',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='group',
            name='fairness_algorithm',
            field=models.CharField(choices=[('time_based', 'Time-based (rotate based on who has been waiting longest)'), ('count_based', 'Count-based (rotate based on who has done the least tasks)'), ('difficulty_based', 'Difficulty-based (assign based on task preferences and difficulty)'), ('weighted', 'Weighted (combine multiple factors like time, count, and preferences)')], default='count_based', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='photo_proof_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='task_proposal_voting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='Optional deep-link URL for this notification.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='original_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='photo_proof',
            field=models.ImageField(blank=True, help_text='Optional photo proof of task completion.', null=True, upload_to='task_proofs/'),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='points_earned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='reassignment_reason',
            field=models.CharField(blank=True, choices=[('swap', 'Swap'), ('emergency', 'Emergency'), ('system', 'System Rebalance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='snooze_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('snoozed', 'Snoozed'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('reassigned', 'Reassigned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='taskswap',
            name='counterpart_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_swaps', to='chore_sync.taskoccurrence'),
        ),
        migrations.AddField(
            model_name='taskswap',
            name='expires_at',
            field=models.DateTimeField(default=chore_sync.models._swap_expiry_default),
        ),
        migrations.AddField(
            model_name='taskswap',
            name='swap_type',
            field=models.CharField(choices=[('direct_swap', 'Direct swap'), ('open_request', 'Open request'), ('emergency', 'Emergency reassignment'), ('system_rebalance', 'System rebalance')], default='direct_swap', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('cooking', 'Cooking'), ('laundry', 'Laundry'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='days_of_week',
            field=models.JSONField(blank=True, help_text="List of weekday abbreviations (['mon','wed','fri']) for custom recurrence.", null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, help_text='Relative difficulty level of the task (for weighted assignment).'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='estimated_mins',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_swap', 'Task swap'), ('group_invite', 'Group invite'), ('task_proposal', 'Task proposal'), ('message', 'Message'), ('deadline_reminder', 'Deadline reminder'), ('emergency_reassignment', 'Emergency reassignment'), ('badge_earned', 'Badge earned'), ('marketplace_claim', 'Marketplace claim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='recurring_choice',
            field=models.CharField(choices=[('none', 'No repeat'), ('weekly', 'Weekly on the same day'), ('monthly', 'Monthly on the same date'), ('every_n_days', 'After x days'), ('custom', 'Custom')], default='none', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='taskoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('snooze_count__lte', 2)), name='snooze_count_max_2'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='chore_sync.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='chore_sync.group'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstats',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_stats', to='chore_sync.group'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge', 'household')},
        ),
        migrations.AlterUniqueTogether(
            name='userstats',
            unique_together={('user', 'household')},
        ),
    ]
