# Generated by Django 5.2.12 on 2026-03-10 21:35

import chore_sync.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0010_badge_userbadge_userstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcredential',
            name='secret',
            field=chore_sync.models.EncryptedJSONField(help_text='Fernet-encrypted JSON blob of OAuth2 tokens'),
        ),
    ]
