# Generated by Django 5.2.12 on 2026-03-10 21:35

from django.db import migrations
from cryptography.fernet import Fernet
import json

def encrypt_existing(apps, schema_editor):
    from django.conf import settings
    ExternalCredential = apps.get_model('chore_sync', 'ExternalCredential')
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    for cred in ExternalCredential.objects.all():
        # cred.secret is currently a raw JSON string in the DB
        encrypted = fernet.encrypt(cred.secret.encode()).decode()
        ExternalCredential.objects.filter(pk=cred.pk).update(secret=encrypted)

class Migration(migrations.Migration):
    dependencies = [
        ('chore_sync', '0011_alter_externalcredential_secret'),  
    ]
    operations = [
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]