# Generated by Django 5.2.12 on 2026-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0012_encrypt_existing_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoccurrence',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the 24-hour deadline reminder was last sent for this occurrence.', null=True),
        ),
    ]
