# Generated by Django 5.2.12 on 2026-03-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0013_add_reminder_sent_at_to_task_occurrence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='writable',
            new_name='push_enabled',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='back_sync_enabled',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='sync_enabled',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='sync_token',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='watch_expires_at',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='webhook_token',
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_task_writeback',
            field=models.BooleanField(default=False, help_text='If True, task occurrences assigned to this user are written back to this calendar.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', help_text='Optional deep-link path or URL for this notification.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='GoogleCalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_token', models.CharField(blank=True, max_length=512, null=True)),
                ('checkpoint_date', models.DateField(blank=True, help_text='Furthest date processed during initial back-fill; resume point on restart.', null=True)),
                ('active_task_id', models.CharField(blank=True, help_text='Celery task ID of the running initial sync — prevents double-queueing.', max_length=255, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('watch_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_token', models.CharField(blank=True, max_length=255, null=True)),
                ('paused', models.BooleanField(default=False, help_text='True while initial sync is running; suppresses concurrent webhook syncs.')),
                ('oauth_writable', models.BooleanField(default=False, help_text='Cached from Google accessRole — True if owner or writer.')),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sync', to='chore_sync.calendar')),
            ],
            options={
                'verbose_name': 'Google Calendar Sync State',
                'verbose_name_plural': 'Google Calendar Sync States',
            },
        ),
        migrations.CreateModel(
            name='OutlookCalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_link', models.TextField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_sync', to='chore_sync.calendar')),
            ],
            options={
                'verbose_name': 'Outlook Calendar Sync State',
                'verbose_name_plural': 'Outlook Calendar Sync States',
            },
        ),
    ]
