# Generated by Django 5.2.12 on 2026-03-22 12:52

from django.db import migrations


def backfill_internal_writeback(apps, schema_editor):
    """
    For every user whose internal calendar does not already have is_task_writeback=True,
    set it. Each user should have exactly one internal calendar (created on signup).
    If a user has multiple internal calendars (shouldn't happen), only the first is flagged.
    """
    Calendar = apps.get_model('chore_sync', 'Calendar')
    User = apps.get_model('chore_sync', 'User')

    for user in User.objects.all():
        internal_cals = Calendar.objects.filter(user=user, provider='internal').order_by('id')
        if not internal_cals.exists():
            # User predates the internal calendar feature — create one now.
            Calendar.objects.create(
                user=user,
                provider='internal',
                name=f"{user.username}'s calendar",
                color='grey',
                timezone=getattr(user, 'timezone', 'UTC') or 'UTC',
                is_task_writeback=True,
            )
        else:
            # Mark the first internal calendar as the writeback target.
            first = internal_cals.first()
            if not first.is_task_writeback:
                first.is_task_writeback = True
                first.save(update_fields=['is_task_writeback'])


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0014_step17_calendar_refactor'),
    ]

    operations = [
        migrations.RunPython(backfill_internal_writeback, migrations.RunPython.noop),
    ]
