# Generated by Django 5.2.12 on 2026-03-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0015_backfill_internal_calendar_writeback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='photo_proof_required',
            field=models.BooleanField(default=False, help_text='If True, the assignee must upload a photo when marking this task complete.'),
        ),
    ]
