# Generated by Django 5.2.12 on 2026-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0016_add_photo_proof_to_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='emoji',
            field=models.CharField(blank=True, help_text='Single emoji displayed in UI', max_length=8),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
