# Generated by Django 5.2.12 on 2026-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0017_add_badge_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoccurrence',
            name='reminder_3h_sent',
            field=models.BooleanField(default=False, help_text='Whether the 3-hour-before reminder has been sent.'),
        ),
        migrations.AddField(
            model_name='taskoccurrence',
            name='reminder_due_sent',
            field=models.BooleanField(default=False, help_text='Whether the at-due-time reminder has been sent.'),
        ),
    ]
