# Generated by Django 5.2.12 on 2026-03-23 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0019_add_marketplace_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_reminders', models.BooleanField(default=True)),
                ('task_assigned', models.BooleanField(default=True)),
                ('task_swap', models.BooleanField(default=True)),
                ('emergency_reassign', models.BooleanField(default=True)),
                ('badge_earned', models.BooleanField(default=True)),
                ('marketplace_activity', models.BooleanField(default=True)),
                ('smart_suggestions', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
            },
        ),
    ]
