# Generated by Django 5.2.12 on 2026-03-23 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0020_add_notification_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('was_swapped', models.BooleanField(default=False)),
                ('was_emergency', models.BooleanField(default=False)),
                ('was_marketplace', models.BooleanField(default=False)),
                ('task_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='chore_sync.taskoccurrence')),
                ('task_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='chore_sync.tasktemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'task_template', 'assigned_at'], name='chore_sync__user_id_9c2fee_idx')],
            },
        ),
    ]
