# Generated by Django 5.2.12 on 2026-03-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0021_add_task_assignment_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupCalendar',
        ),
    ]
