# Generated by Django 5.2.12 on 2026-03-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0024_taskoccurrence_suggestion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_swap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chore_sync.taskswap'),
        ),
    ]
