# Generated by Django 5.2.12 on 2026-04-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0027_cleanup_calendar_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskoccurrence',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('snoozed', 'Snoozed'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], default='suggested', max_length=20),
        ),
    ]
