# Generated by Django 5.2.12 on 2026-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0028_alter_taskoccurrence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo. Populated from SSO provider on first sign-in.', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='External avatar URL (e.g. from Google/Microsoft). Used when no uploaded avatar is present.', max_length=500),
        ),
    ]
