# Generated by Django 5.2.12 on 2026-04-07 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0029_add_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskproposal',
            name='required_support_ratio',
        ),
        migrations.RemoveField(
            model_name='taskproposal',
            name='voting_deadline',
        ),
        migrations.AddField(
            model_name='group',
            name='auto_moderator',
            field=models.BooleanField(default=False, help_text='When True, anyone who joins via invite code is automatically assigned the moderator role (suitable for flat/equal groups like flatshares).'),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='approval_note',
            field=models.TextField(blank=True, default='', help_text="Moderator's note explaining edits or rejection reason."),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who approved or rejected this proposal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='approved_payload',
            field=models.JSONField(blank=True, help_text='Moderator-edited task details. Null means approved as-is. When set, diff against proposed_payload is the audit log.', null=True),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='proposed_payload',
            field=models.JSONField(default=dict, help_text='Full task details as submitted by the proposer — frozen after creation. Keys mirror TaskTemplate fields: name, category, difficulty, estimated_mins, recurring_choice, recur_value, days_of_week, next_due, details.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='task_proposal_voting_required',
            field=models.BooleanField(default=False, help_text='When True, only moderators can create tasks directly. Members must submit suggestions which moderators approve or reject.'),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this suggestion (may be null if deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='reason',
            field=models.TextField(blank=True, help_text="Proposer's explanation for why this task should be added."),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='task_template',
            field=models.ForeignKey(blank=True, help_text='The TaskTemplate created when this proposal was approved (null until approved).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='chore_sync.tasktemplate'),
        ),
    ]
