# Generated by Django 5.2.12 on 2026-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0030_proposal_approval_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='auto_moderator',
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('flatshare', 'Flat Share'), ('family', 'Family'), ('work_team', 'Work Team'), ('custom', 'Custom')], default='custom', help_text='Determines join behaviour and invite-UI role labels. flatshare: everyone joins as moderator. family/work_team/custom: owner chooses role per invite.', max_length=20),
        ),
    ]
