# Generated by Django 5.2.12 on 2026-04-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0032_user_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='fairness_algorithm',
        ),
    ]
