# Generated by Django 5.2.12 on 2026-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0033_remove_fairness_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignmenthistory',
            name='score_breakdown',
            field=models.JSONField(blank=True, help_text='Per-candidate pipeline scores at assignment time. Keys: winner_id (str), candidates (list of dicts with user_id, username, stage1_score, pref_multiplier, affinity_multiplier, calendar_penalty, final_score). Null for rows created outside the pipeline (swaps, emergency, marketplace).', null=True),
        ),
    ]
