# Generated by Django 5.2.12 on 2026-04-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0035_remove_group_photo_proof_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='task_proposal_voting_required',
        ),
        migrations.DeleteModel(
            name='TaskVote',
        ),
    ]
