# Generated by Django 5.2.12 on 2026-04-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0037_add_group_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='importance',
        ),
    ]
