# Generated by Django 5.2.12 on 2026-04-18 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0038_remove_task_template_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproposal',
            name='vote_deadline',
            field=models.DateTimeField(blank=True, help_text='When the voting window closes. Computed at submission time.', null=True),
        ),
        migrations.AddField(
            model_name='taskproposal',
            name='vote_mode',
            field=models.BooleanField(default=False, help_text='When True the proposal goes to a group vote rather than moderator review.'),
        ),
        migrations.AlterField(
            model_name='taskproposal',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('voting', 'Voting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current approval state of the proposal.', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chore_sync.taskproposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
