# Generated by Django 5.2.12 on 2026-04-25 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0040_simplify_reassignment_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Account registered'), ('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('email_verified', 'Email verified'), ('email_updated', 'Email updated'), ('password_reset_requested', 'Password reset requested'), ('password_reset_used', 'Password reset used'), ('password_changed', 'Password changed'), ('google_sso_login', 'Google SSO login'), ('microsoft_sso_login', 'Microsoft SSO login'), ('google_calendar_connected', 'Google Calendar connected'), ('microsoft_calendar_connected', 'Microsoft Calendar connected')], db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth Event',
                'verbose_name_plural': 'Auth Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
