# Generated by Django 5.2.12 on 2026-04-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0041_add_auth_event_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='action',
            field=models.CharField(choices=[('register', 'Account registered'), ('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('email_verified', 'Email verified'), ('email_updated', 'Email updated'), ('password_reset_requested', 'Password reset requested'), ('password_reset_used', 'Password reset used'), ('password_changed', 'Password changed'), ('google_sso_login', 'Google SSO login'), ('microsoft_sso_login', 'Microsoft SSO login'), ('google_calendar_connected', 'Google Calendar connected'), ('microsoft_calendar_connected', 'Microsoft Calendar connected'), ('token_refreshed', 'JWT token refreshed')], db_index=True, max_length=40),
        ),
    ]
