# Generated by Django 5.2.12 on 2026-04-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_sync', '0047_drop_externalcredential_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID used by external provider to identify the calendar', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='externalcredential',
            name='last_refreshed_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last save on this credential (auto-updated on every save, not just token refreshes).'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='taskoccurrence',
            name='snooze_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
