apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: choresync-frontend
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: VITE_API_BASE_URL
          value: "https://choresync.mahamadahir.com"
        - name: VITE_GOOGLE_CLIENT_ID
          value: "718861309094-rdmdpjcb0475vjcoc8h4agfis3uo50bs.apps.googleusercontent.com"
        - name: VITE_MSAL_CLIENT_ID
          value: "07637169-b2bb-43e8-84d5-2854af3c34f3"
        - name: VITE_MSAL_AUTHORITY
          value: "https://login.microsoftonline.com/common"
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: choresync-frontend:latest
